openapi: 3.0.0
info:
  description: Documentação do Desafio
  title: Lista de compras - API Docs
  version: 0.0.1

servers:
  - url: /api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Sanctum

paths:
  /auth/login:
    $ref: 'routes/auth/login/actions.yaml'
  /auth/register:
    $ref: 'routes/auth/register/actions.yaml'
  /auth/logout:
    $ref: 'routes/auth/logout/actions.yaml'
  /products:
    $ref: 'routes/products/actions.yaml'
  /products/{id}:
    $ref: 'routes/products/id/actions.yaml'
  /shopping_lists:
    $ref: 'routes/shopping_lists/actions.yaml'
  /shopping_lists/{id}:
    $ref: 'routes/shopping_lists/id/actions.yaml'
  /shopping_lists/{id}/checkout:
    $ref: 'routes/shopping_lists/id/checkout/actions.yaml'
  /shopping_lists/{id}/products:
    $ref: 'routes/shopping_lists/id/products/actions.yaml'

